    class_<DvrGrid>("dvrGrid", init<>())
        .def(init<blas_int>())
        .def(init<def_float, def_float, blas_int>())
        .def(init<const DvrGrid&>())
        .def("swap",    &DvrGrid::swap,   return_internal_reference<>())
        .def("copy",    &DvrGrid::copy)
        .def("x",       &DvrGrid::x)
        .def("w",       &DvrGrid::w)
        .def("nq",      &DvrGrid::quadrature)
    ;

    class_<femGrid>("grid", init<>())
        .def(init<const int, const int, iVector&, dVector&, double>())
        .def(init<parameters::grid<double>&>())
        .def(init<const femGrid&>())
        .def("swap",    &femGrid::swap,     return_internal_reference<>())
        .def("xr",      &femGridxr)
        .def("x",       &femGridx)
        .def("w",       &femGridw)
        .def("nel",     &femGridnel)
        .def("ar",      &femGridar)
        .def("aaz",     &femGridaaz)
        .def("wq",      &femGrid::wq)
        .def("nb",      &femGrid::nb)
        .def("nq",      &femGrid::quadrature)
        .def("tnel",    &femGrid::tnel)
        .def("nr",      &femGrid::nr)
        .def("xpos",    &femGridx_pos)
        .def("xneg",    &femGridx_neg)
        .def("elementEnd",      &femGrid::get_element_end)
        .def("elementStart",    &femGrid::get_element_start)
        .def("xElementIndex",   &femGrid::get_element_index)
        .def("xElementEnd",     &femGrid::get_element_end_x)
        .def("xElementStart",   &femGrid::get_element_start_x)
        .def("bfVal",       &femGrid::basis_function_value)
        .def("dlp",        static_cast<const dMatrix& (femGrid::*)() const>(&femGrid::dlp), return_value_policy<reference_existing_object>(), femGridDlp())
        //.def("dlp",        static_cast<const def_float& (femGrid::*)(const blas_int& i, const blas_int& j) const>(&femGrid::dlp), femGridDlp())
        .def("export",      &femGridExport)
        .def("save",        static_cast<bool(femGrid::*)(const char*) const>(&femGrid::save_binary), femGridSave())
        .def("load",        static_cast<bool(femGrid::*)(const char*)>(&femGrid::read_binary), femGridLoad())
    ;

    def("gridFromString", &gridFromString);

    class_<gVector>("gVector", init<>())
        .def(init<femGrid&>())
        .def(init<femGrid&, zVector&>())
        .def(init<femGrid&, zVector&, bool>())
        .def(init<const gVector&>())
        .def("grid",        &gVector::get_grid,                     return_value_policy<reference_existing_object>())
        .def("body",        static_cast<zVector& (gVector::*)()>(&gVector::body), return_value_policy<reference_existing_object>(), gVectorBody())
        .def("ewMult",      &gVector::element_wise_multiplication,  return_internal_reference<>())
        .def("swap",        &gVector::swap,                         return_internal_reference<>())
        .def(self+=self)
        .def(self-=self)
        .def(self*=other<dComplex>())
        .def("fill",        &gVector::fill,                 return_internal_reference<>())
        .def("axpy",        &gVector::axpy,                 return_internal_reference<>())
        .def("ax",          &gVector::ax,                   return_internal_reference<>())
        .def("copy",        &gVector::copy)
        .def("normsq",      &gVector::get_norm)
        .def("__getitem__", &gVectorGetItem)
        .def("__setitem__", &gVectorSetItem,                return_internal_reference<>())
        .def("getVal",      static_cast<def_comp (gVector::*)(blas_int) const>(&gVector::f), gVectorValue())
        .def("setVal",      static_cast<void (gVector::*)(const def_comp&, blas_int)>(&gVector::f), gVectorValue2())
        .def(self*self)
        //.def("__imul__",    &gVector::diagMul,             return_internal_reference<>())  // TODO rmul
        //.def("__imul__",    &gVector::fullMul,             return_internal_reference<>())  // TODO rmul
        //.def("__idiv__",    &gVector::fullDiv,             return_internal_reference<>())
        .def("df",          &gVector::derivative)
        .def("eval",        &gVector::evaluate)
        .def("save",        &gVector::save,                return_internal_reference<>())
        .def("saveEq",      &gVector::save_equidistant,     return_internal_reference<>())
        .def("size",        &gVector::get_size)
        .def("savetxt",     &gVector::save)
        .def("save",        static_cast<bool(gVector::*)(const char*) const>(&gVector::save_binary), gVectorSave())
        .def("load",        static_cast<bool(gVector::*)(const char*)>(&gVector::read_binary), gVectorLoad())
        .def("export",      &gVectorExportSimple)
        .def("export",      &gVectorExportRange)
    ;

    class_<zOperatorD>("dOperator", init<>())
        .def(init<femGrid&>())
        .def(init<femGrid&, const int, const int>())
        .def("id",      &zOperatorD::identity,         return_internal_reference<>())
        .def("swap",    &zOperatorD::swap,             return_internal_reference<>())
        .def("grid",        &gVector::get_grid,                     return_value_policy<reference_existing_object>())
        .def("set",     static_cast<zOperatorD& (zOperatorD::*)(const def_comp&)>(&zOperatorD::operator=), return_internal_reference<>(), zOperatorDSet())
        .def("set",     static_cast<zOperatorD& (zOperatorD::*)(const zVector&)>(&zOperatorD::operator=), return_internal_reference<>(), zOperatorDSet())
        .def("set",     static_cast<zOperatorD& (zOperatorD::*)(const gVector&)>(&zOperatorD::operator=), return_internal_reference<>(), zOperatorDSet())
        .def(self+=self)
        .def(self+=other<def_comp>())
        .def(self+=other<zVector>())
        .def(self+=other<gVector>())
        .def(self-=self)
        .def(self-=other<def_comp>())
        .def(self-=other<zVector>())
        .def(self-=other<gVector>())
        .def(self*=self)
        .def(self*=other<def_comp>())
        .def("inverse",         &zOperatorD::inverse,           return_internal_reference<>())
        .def("__getitem__",     &zOperatorDGetItem)
        .def("__setitem__",     &zOperatorDSetItem,             return_internal_reference<>())
        .def("size",            &zOperatorD::get_size)
        .def("shift",           &zOperatorD::get_shift)
    ;

    class_<zOperatorF>("fOperator", init<>())
        .def(init<const zOperatorF&>())
        .def(init<femGrid&>())
        .def(init<femGrid&, const int, const int>())
        .def("id",              &zOperatorF::set_identity,      return_internal_reference<>())
        .def("transpose",       &zOperatorF::transpose,         return_internal_reference<>())
        .def("swap",            &zOperatorF::swap,              return_internal_reference<>())
        .def("grid",            &zOperatorF::get_grid,          return_value_policy<reference_existing_object>())
        .def("outer_product",   &zOperatorF::outer_product,     return_internal_reference<>())
        .def("set",     static_cast<zOperatorF& (zOperatorF::*)(const def_comp&)>(&zOperatorF::operator=), return_internal_reference<>(), zOperatorFSet())
        .def("set",     static_cast<zOperatorF& (zOperatorF::*)(const zVector&)>(&zOperatorF::operator=), return_internal_reference<>(), zOperatorFSet())
        .def("set",     static_cast<zOperatorF& (zOperatorF::*)(const gVector&)>(&zOperatorF::operator=), return_internal_reference<>(), zOperatorFSet())
        .def("set",     static_cast<zOperatorF& (zOperatorF::*)(const zOperatorD&)>(&zOperatorF::operator=), return_internal_reference<>(), zOperatorFSet())
        .def("copy",            &zOperatorF::copy)
        .def(self+=self)
        .def(self+=other<zOperatorD>())
        .def(self+=other<zVector>())
        .def(self+=other<gVector>())
        .def(self+=other<dComplex>())
        .def(self-=self)
        .def(self-=other<zOperatorD>())
        .def(self-=other<zVector>())
        .def(self-=other<gVector>())
        .def(self-=other<dComplex>())
        .def(self*=self)
        .def("__getitem__",     &zOperatorFGetItem)
        .def("__setitem__",     &zOperatorFSetItem,             return_internal_reference<>())
        .def("inverse",         &zOperatorF::inverse,           return_internal_reference<>())
        .def("eigen_system",    &zOperatorF::eigen_system)
        .def("LU",              &zOperatorF::LU_factorize,      return_internal_reference<>())
        .def("addKineticTerm",  &zOperatorF::add_kinetic_term,  return_internal_reference<>())
        .def("gemv",            &zOperatorF::gemv,              return_internal_reference<>())
        .def("size",            &zOperatorF::get_size)
        .def("shift",           &zOperatorF::get_shift)
    ;

    class_<zOperatorC>("rcOperator", init<>())
        .def(init<const zOperatorC&>())
        .def(init<femGrid&, const int, const int>())
        .def(self+=other<gVector>())
        .def(self+=other<dComplex>())
        .def(self*=other<dComplex>())
        .def("set_kinetic_term",    &zOperatorC::set_kinetic_term, return_internal_reference<>())
        .def("gemv",            &zOperatorC::gemv)
        .def("size",            &zOperatorC::get_size)
        .def("shift",           &zOperatorC::get_shift)
        .def("grid",            &zOperatorC::get_grid,        return_value_policy<reference_existing_object>())
        //.def("id",              &zOperatorC::set_identity,    return_internal_reference<>())
        .def("swap",            &zOperatorC::swap,            return_internal_reference<>())
        .def("LU",              &zOperatorC::LU_factorize)
        .def("back_substitute", &zOperatorC::LU_back_substitution)
        .def("export",          &rcOperatorExport)
    ;
