
    class_<femGrid2D>("grid2d", init<>())
        .def(init<femGrid&, femGrid&>())
        .def(init<const femGrid2D&>())
        .def("xr",      &femGrid2Dxr)
        .def("yr",      &femGrid2Dyr)
        .def("xz",      &femGrid2Dxz)
        .def("yz",      &femGrid2Dyz)
        .def("xwz",     &femGrid2Dxwz)
        .def("ywz",     &femGrid2Dywz)
        .def("gridX",   &femGrid2D::get_xgrid,  return_internal_reference<>())
        .def("gridY",   &femGrid2D::get_ygrid,  return_internal_reference<>())
        .def("wz",      static_cast<def_comp (femGrid2D::*)(blas_int) const>(&femGrid2D::wz), femGrid2DWeight())
        .def("wz",      static_cast<def_comp (femGrid2D::*)(blas_int, blas_int) const>(&femGrid2D::wz), femGrid2DWeight())
        .def("nb",      &femGrid2D::get_size)
        .def("nbx",     &femGrid2D::get_xsize)
        .def("nby",     &femGrid2D::get_ysize)
        .def("save",    static_cast<bool(femGrid2D::*)(const char*) const>(&femGrid2D::save_binary), femGrid2DSave())
        .def("load",    static_cast<bool(femGrid2D::*)(const char*)>(&femGrid2D::read_binary), femGrid2DLoad())
        .def("export",  &femGrid2DExport)
    ;

    class_<gVector2D>("gVector2d", init<>())
        .def(init<femGrid2D&>())
        .def(init<const gVector2D>())
        .def(self+=self)
        .def(self-=self)
        .def(self*=other<dComplex>())
        .def("axpy",    &gVector2D::axpy,  return_internal_reference<>())
        .def("ax",      &gVector2D::ax,    return_internal_reference<>())
        .def("copy",    &gVector2D::copy)
        .def("swap",    &gVector2D::swap,  return_internal_reference<>())
        .def("grid",    &gVector2D::get_grid, return_internal_reference<>())
        .def(self*self)
        .def("__getitem__", &gVector2DGetItem)
        .def("__setitem__", &gVector2DSetItem,      return_internal_reference<>())
        .def("export",  &gVector2DExportRange)
        .def("set",     &gVector2DSetValues,        return_internal_reference<>())
        .def("nbx",     &gVector2D::get_xsize)
        .def("nby",     &gVector2D::get_ysize)
        .def("write_x", &gVector2D::write_x_section, return_internal_reference<>())
        .def("read_x",  &gVector2D::get_x_section)
        //.def("body",    &gVector2D::constBodyRef,  return_internal_reference<>())
        //.def("body",    &gVector2D::bodyRef,       return_internal_reference<>())
        .def("savetxt",     &gVector2D::save)
        .def("save",        static_cast<bool(gVector2D::*)(const char*) const>(&gVector2D::save_binary), gVector2DSave())
        .def("load",        static_cast<bool(gVector2D::*)(const char*)>(&gVector2D::read_binary), gVector2DLoad())
    ;

    class_<zOperator2D>("operator2d", init<>())
        .def(init<femGrid2D&>())
        .def(init<const zOperator2D&>())
        .def(self*=other<dComplex>())
        .def(self+=other<gVector2D>())
        .def(self+=other<zVector>())
        .def(self*other<gVector2D>())
        .def("set_kinetic_term",    &zOperator2D::set_kinetic_term,    return_internal_reference<>())
        .def("gemv",                &zOperator2D::gemv)
        .def("LU",                  &zOperator2D::LU_factorize)
        .def("back_substitute",     &zOperator2D::LU_back_substitution)
        .def("export",              &rcOperator2dExport)
        //.def("body",            &rcOperator2dPy::constBodyRef,  return_internal_reference<>())
        //.def("body",            &rcOperator2dPy::bodyRef,       return_internal_reference<>())
    ;

    class_<EProjector2d>("projectorE2d", init<const femGrid2D&, size_t, size_t, dfloat, dfloat, dfloat, dfloat>())
        .def("export",              &EProjector2d::Export)
        //.def("body",            &rcOperator2dPy::constBodyRef,  return_internal_reference<>())
        //.def("body",            &rcOperator2dPy::bodyRef,       return_internal_reference<>())
    ;
