"""Machinery tests for the numeric-output + visualization layer (Task 6).

No pass/fail on physics shape here (that's Tasks 4/5's job) -- these tests
check that `save_numeric_outputs` round-trips, that re-transforming the
SAVED `c(t)` reproduces the SAVED `sigma_E` (V5 self-consistency: the stored
numeric time series is consistent with the reported curve), that densities
are real/non-negative, and that the three plot functions produce non-empty
PNG files. Everything here uses a TINY, fast propagation (few steps, small
grid) -- the real converged-grid figures are generated by a separate script,
not by this test module (see the development notes).
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest
from qscat.dvr import TensorGrid

from projects.n2_2d_cross_section.electronic_grid import n2_electronic_grid
from projects.n2_2d_cross_section.hamiltonian2d import MU
from projects.n2_2d_td_cross_section.correlation import outgoing_channel
from projects.n2_2d_td_cross_section.observation import (
    plot_correlation,
    plot_sigma_vs_ti,
    plot_snapshots,
    save_numeric_outputs,
)
from projects.n2_2d_td_cross_section.td_cross_section import sigma_from_correlations
from projects.n2_2d_td_cross_section.td_propagation import PropagationResult, propagate
from projects.n2_2d_td_cross_section.wavepacket import initial_state
from projects.n2_ti_cross_section.nuclear_grid import n2_nuclear_grid
from projects.n2_ti_cross_section.vibrational import vibrational_states

# A small, fast grid -- same family as test_td_propagation.py's, just for
# machinery, not physics-convergence assertions.
TG: TensorGrid = TensorGrid(
    [
        n2_electronic_grid(r_max=20.0, order=8, n_complex=3),
        n2_nuclear_grid(quadrature=8, r_max=14.0, n_complex=2),
    ]
)
EPS, CHI = vibrational_states(TG.grids[1], MU, 4)

V_INIT = 0
VPRIMES = [1]
WP_IN = {"r0": 12.0, "p0": -0.5, "sigma": 2.0}
WP_OUT = {"r0_out": 15.0, "p0_out": 0.5, "sigma_out": 2.0}
DT = 1.0
N_STEPS = 6


def _tiny_result() -> PropagationResult:
    psi0 = initial_state(TG, CHI[V_INIT], **WP_IN)
    out_channels = [outgoing_channel(TG, CHI[vp], **WP_OUT) for vp in VPRIMES]
    return propagate(TG, psi0, out_channels, dt=DT, n_steps=N_STEPS, snapshot_times=[0.0, 3.0, 6.0])


def _sigma_at(result: PropagationResult, e_grid: np.ndarray) -> np.ndarray:
    return sigma_from_correlations(
        TG, result, EPS, V_INIT, VPRIMES, e_grid, dt=DT, wp_in=WP_IN, wp_out=WP_OUT
    )


def test_npz_round_trips(tmp_path: Path) -> None:
    result = _tiny_result()
    e_grid = np.array([0.05, 0.08])
    sigma_e = _sigma_at(result, e_grid)

    out = tmp_path / "numeric.npz"
    save_numeric_outputs(result, sigma_e, e_grid, out, dt=DT, wp_in=WP_IN, wp_out=WP_OUT)
    assert out.exists() and out.stat().st_size > 0

    with np.load(out) as data:
        assert set(data.files) >= {
            "t",
            "c",
            "norm",
            "times",
            "rho_R",
            "rho_r",
            "E_grid",
            "sigma_E",
            "dt",
            "wp_in",
            "wp_out",
        }
        assert float(data["dt"]) == DT
        assert json.loads(str(data["wp_in"])) == WP_IN
        assert json.loads(str(data["wp_out"])) == WP_OUT
        np.testing.assert_array_equal(data["t"], result.t)
        np.testing.assert_array_equal(data["c"], result.c)
        np.testing.assert_array_equal(data["norm"], result.norm)
        np.testing.assert_array_equal(data["times"], np.array([s.time for s in result.snapshots]))
        np.testing.assert_array_equal(data["rho_R"], np.stack([s.rho_R for s in result.snapshots]))
        np.testing.assert_array_equal(data["rho_r"], np.stack([s.rho_r for s in result.snapshots]))
        np.testing.assert_array_equal(data["E_grid"], e_grid)
        np.testing.assert_array_equal(data["sigma_E"], sigma_e)


def test_v5_saved_c_reproduces_saved_sigma(tmp_path: Path) -> None:
    """Re-transforming the SAVED c(t) (same eta/quadrature) reproduces the
    SAVED sigma_E to round-off -- the stored numeric time series is
    consistent with the reported curve."""
    result = _tiny_result()
    e_grid = np.array([0.05, 0.08, 0.12])
    sigma_e = _sigma_at(result, e_grid)

    out = tmp_path / "numeric.npz"
    save_numeric_outputs(result, sigma_e, e_grid, out, dt=DT, wp_in=WP_IN, wp_out=WP_OUT)

    # Reload EVERYTHING the transform needs (incl. dt/wp_in/wp_out) purely
    # from the .npz -- proves the file is self-contained for re-transform.
    with np.load(out) as data:
        reloaded = PropagationResult(t=data["t"], c=data["c"], norm=data["norm"], snapshots=[])
        reloaded_e_grid = data["E_grid"]
        reloaded_sigma = data["sigma_E"]
        reloaded_dt = float(data["dt"])
        reloaded_wp_in = json.loads(str(data["wp_in"]))
        reloaded_wp_out = json.loads(str(data["wp_out"]))

    retransformed = sigma_from_correlations(
        TG,
        reloaded,
        EPS,
        V_INIT,
        VPRIMES,
        reloaded_e_grid,
        dt=reloaded_dt,
        wp_in=reloaded_wp_in,
        wp_out=reloaded_wp_out,
    )
    np.testing.assert_allclose(retransformed, reloaded_sigma, rtol=1e-12, atol=1e-14)
    np.testing.assert_allclose(retransformed, sigma_e, rtol=1e-12, atol=1e-14)


def test_densities_real_and_nonnegative() -> None:
    result = _tiny_result()
    assert len(result.snapshots) > 0
    for snap in result.snapshots:
        assert snap.rho_R.dtype == np.float64
        assert snap.rho_r.dtype == np.float64
        assert np.all(np.isfinite(snap.rho_R)) and np.all(snap.rho_R >= 0.0)
        assert np.all(np.isfinite(snap.rho_r)) and np.all(snap.rho_r >= 0.0)


def test_plot_snapshots_produces_nonempty_png(tmp_path: Path) -> None:
    result = _tiny_result()
    out = tmp_path / "snapshots.png"
    plot_snapshots(result, out)
    assert out.exists() and out.stat().st_size > 0


def test_plot_snapshots_with_tgrid_produces_nonempty_png(tmp_path: Path) -> None:
    result = _tiny_result()
    out = tmp_path / "snapshots_tgrid.png"
    plot_snapshots(result, out, tgrid=TG)
    assert out.exists() and out.stat().st_size > 0


def test_plot_correlation_produces_nonempty_png(tmp_path: Path) -> None:
    result = _tiny_result()
    out = tmp_path / "correlation.png"
    plot_correlation(result, out)
    assert out.exists() and out.stat().st_size > 0


def test_plot_sigma_vs_ti_produces_nonempty_png(tmp_path: Path) -> None:
    e_grid = np.array([0.03, 0.05, 0.08, 0.10, 0.12, 0.15])
    sigma_td = np.array([0.5, 1.2, 2.0, 1.8, 1.0, 0.3])
    sigma_ti = np.array([0.4, 1.1, 2.1, 1.9, 0.9, 0.25])
    usable = (0.05, 0.12)
    out = tmp_path / "sigma.png"
    plot_sigma_vs_ti(e_grid, sigma_td, sigma_ti, usable, out)
    assert out.exists() and out.stat().st_size > 0


def test_plot_sigma_vs_ti_multichannel_produces_nonempty_png(tmp_path: Path) -> None:
    e_grid = np.array([0.03, 0.05, 0.08, 0.10])
    sigma_td = np.array([[0.5, 0.1], [1.2, 0.2], [2.0, 0.3], [1.8, 0.25]])
    sigma_ti = sigma_td * 0.95
    usable = (0.05, 0.10)
    out = tmp_path / "sigma_multi.png"
    plot_sigma_vs_ti(e_grid, sigma_td, sigma_ti, usable, out)
    assert out.exists() and out.stat().st_size > 0


def test_plot_correlation_rejects_mismatched_labels() -> None:
    result = _tiny_result()
    with pytest.raises(ValueError):
        plot_correlation(result, "unused.png", labels=["a", "b", "c"])
