"""Sphinx configuration for the qscat documentation site.

Build locally:

    uv sync --group docs
    uv run sphinx-build -b html docs docs/_build/html

The API reference is generated by autodoc from the qscat source; prose
docstrings render today, and are being converted to numpydoc sections
(roadmap Part 2) for full parameter/return tables.
"""

from __future__ import annotations

import qscat

project = "qscat"
author = "Martin Vana"
copyright = "2026, Martin Vana"  # noqa: A001 - Sphinx expects this name
release = qscat.__version__
version = ".".join(release.split(".")[:2])

extensions = [
    "myst_parser",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
    "sphinx.ext.mathjax",
]

autosummary_generate = True
autodoc_typehints = "description"
autodoc_member_order = "bysource"
napoleon_google_docstring = True
napoleon_numpy_docstring = True

myst_enable_extensions = ["dollarmath", "colon_fence"]

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
}

templates_path = ["_templates"]
# The site is index/getting-started/api/physics (Theory). physics/ is now
# published as the site's Theory section; adr/ and superpowers/ remain
# repository-only docs (ADRs, specs) — excluded so Sphinx doesn't warn about
# them being outside any toctree.
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "adr",
    "superpowers",
]

html_theme = "furo"
html_title = f"qscat {release}"
