"""Sphinx configuration for the qscat documentation site.

Build locally:

    uv sync --all-packages --group docs
    uv run sphinx-build -b html docs docs/_build/html

The API reference is generated by autodoc from the qscat source; prose
docstrings render today, and are being converted to numpydoc sections
(roadmap Part 2) for full parameter/return tables.
"""

from __future__ import annotations

import qscat

project = "qscat"
author = "Martin Vana"
copyright = "2026, Martin Vana"
release = qscat.__version__
version = ".".join(release.split(".")[:2])

extensions = [
    "myst_parser",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
    "sphinx.ext.mathjax",
    "sphinx.ext.githubpages",
    "sphinx_copybutton",
    "sphinx_design",
    "sphinxext.opengraph",
]

autosummary_generate = True
autodoc_typehints = "description"
autodoc_member_order = "bysource"
# numpydoc is the ONE docstring dialect (ruff D convention = "numpy");
# google-style parsing off so a stray google-section renders wrong loudly
# instead of silently working.
napoleon_google_docstring = False
napoleon_numpy_docstring = True

# dollarmath: $...$ and $$...$$. colon_fence: ::: directives. deflist:
# definition lists for the symbol table.
#
# NOT amsmath: it parses a BARE \begin{align} block, which github.com does
# not render. The notes are read in two renderers (spec C3), so multi-line
# mathematics is written as $$ \begin{aligned} ... \end{aligned} $$, which
# both handle. One form, no dialect to police.
myst_enable_extensions = ["dollarmath", "colon_fence", "deflist"]

# Number only the equations a note actually cross-references with {eq};
# numbering all of them adds visual noise to notes that never refer back.
numfig = True
math_number_all = False
math_eqref_format = "Eq. {number}"

# No mathjax3_config macros are defined, deliberately: a macro renders on
# the site but not on github.com, and the notes must render in both
# (spec D1). Equations spell \Psi^{(+)} and \sigma_\mathrm{DA} out longhand.

# Strip interpreter and shell prompts so a copied block is runnable.
copybutton_prompt_text = r">>> |\.\.\. |\$ "
copybutton_prompt_is_regexp = True

html_baseurl = "https://vanamartin.github.io/qscat/"
ogp_site_url = html_baseurl
ogp_description_length = 200

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
}

templates_path = ["_templates"]
# The site is index/getting-started/api/physics (Theory). physics/ is now
# published as the site's Theory section; adr/ and superpowers/ remain
# repository-only docs (ADRs, specs) — excluded so Sphinx doesn't warn about
# them being outside any toctree.
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "adr",
    "superpowers",
]

html_theme = "furo"
html_title = f"qscat {release}"
html_theme_options = {
    "source_repository": "https://github.com/VanaMartin/qscat/",
    "source_branch": "main",
    "source_directory": "docs/",
    "light_css_variables": {
        "color-brand-primary": "#1a5490",
        "color-brand-content": "#1a5490",
    },
    "dark_css_variables": {
        "color-brand-primary": "#7cb3e8",
        "color-brand-content": "#7cb3e8",
    },
}

# Intersphinx fetches each project's `objects.inv` over the network at build
# time, so a third party's uptime is part of this repository's docs gate: when
# `docs.scipy.org` times out, intersphinx logs `failed to reach any of the
# inventories`, `-W` turns that one warning into an error, and a pull request
# that never touched the docs goes red. It has done so on unrelated branches
# and on `main`.
#
# The links are worth keeping -- the Python inventory alone resolves ~1050
# references in the built site, every `float`/`int`/`tuple` in an autodoc
# signature -- so the fix is not to drop intersphinx. Nor can the warning be
# silenced with `suppress_warnings`: Sphinx logs it with no warning type
# (`sphinx/ext/intersphinx/_load.py`), and `suppress_warnings` matches only
# typed warnings. Deciding reachability ourselves before intersphinx runs does
# not work either: a `HEAD` probe answers a different question than the fetch
# does, and measurably disagrees with it -- `numpy.org` returns 403 to plain
# urllib while intersphinx succeeds, and `docs.scipy.org` times out on HEAD
# while GET returns in ~4 s.
#
# So the fetch is left to intersphinx, and only its unreachable-inventory
# record is demoted, on the handler that `-W` promotes from. An unreachable
# inventory costs cross-links into that project's documentation and nothing
# else: unresolved references are not errors unless `nitpicky` is on, and it is
# not. Every other warning still fails the build.
_UNREACHABLE_INVENTORIES = "failed to reach any of the inventories"


def setup(app: object) -> None:
    """Stop a third party's downtime from failing this repository's docs gate."""
    import logging

    class _NetworkIsNotAnError(logging.Filter):
        reported = False

        def filter(self, record: logging.LogRecord) -> bool:
            if _UNREACHABLE_INVENTORIES not in record.getMessage():
                return True
            if not self.reported:  # one instance, three handlers -- say it once
                self.reported = True
                print(
                    "conf.py: intersphinx could not fetch an inventory; cross-links "
                    "into it will be absent from this build, which is not an error"
                )
            return False

    # On the handlers, not the logger: a record logged by a child logger reaches
    # this one only through its parent's handlers. And at the FRONT of the
    # filter chain, not appended -- Sphinx's own `WarningSuppressor` runs first
    # and increments the warning count that `-W` fails on, so a filter added
    # behind it drops the message and still loses the build.
    dropper = _NetworkIsNotAnError()
    for handler in logging.getLogger("sphinx").handlers:
        handler.filters.insert(0, dropper)
