"""Sphinx configuration for the qscat documentation site.

Build locally:

    uv sync --all-packages --group docs
    uv run sphinx-build -b html docs docs/_build/html

The API reference is generated by autodoc from the qscat source; prose
docstrings render today, and are being converted to numpydoc sections
(roadmap Part 2) for full parameter/return tables.
"""

from __future__ import annotations

import qscat

project = "qscat"
author = "Martin Vana"
copyright = "2026, Martin Vana"
release = qscat.__version__
version = ".".join(release.split(".")[:2])

extensions = [
    "myst_parser",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
    "sphinx.ext.mathjax",
    "sphinx.ext.githubpages",
    "sphinx_copybutton",
    "sphinx_design",
    "sphinxext.opengraph",
]

autosummary_generate = True
autodoc_typehints = "description"
autodoc_member_order = "bysource"
# numpydoc is the ONE docstring dialect (ruff D convention = "numpy");
# google-style parsing off so a stray google-section renders wrong loudly
# instead of silently working.
napoleon_google_docstring = False
napoleon_numpy_docstring = True

# dollarmath: $...$ and $$...$$. colon_fence: ::: directives. deflist:
# definition lists for the symbol table.
#
# NOT amsmath: it parses a BARE \begin{align} block, which github.com does
# not render. The notes are read in two renderers (spec C3), so multi-line
# mathematics is written as $$ \begin{aligned} ... \end{aligned} $$, which
# both handle. One form, no dialect to police.
myst_enable_extensions = ["dollarmath", "colon_fence", "deflist"]

# Number only the equations a note actually cross-references with {eq};
# numbering all of them adds visual noise to notes that never refer back.
numfig = True
math_number_all = False
math_eqref_format = "Eq. {number}"

# No mathjax3_config macros are defined, deliberately: a macro renders on
# the site but not on github.com, and the notes must render in both
# (spec D1). Equations spell \Psi^{(+)} and \sigma_\mathrm{DA} out longhand.

# Strip interpreter and shell prompts so a copied block is runnable.
copybutton_prompt_text = r">>> |\.\.\. |\$ "
copybutton_prompt_is_regexp = True

html_baseurl = "https://vanamartin.github.io/qscat/"
ogp_site_url = html_baseurl
ogp_description_length = 200

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
}

templates_path = ["_templates"]
# The site is index/getting-started/api/physics (Theory). physics/ is now
# published as the site's Theory section; adr/ and superpowers/ remain
# repository-only docs (ADRs, specs) — excluded so Sphinx doesn't warn about
# them being outside any toctree.
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "adr",
    "superpowers",
]

html_theme = "furo"
html_title = f"qscat {release}"
html_theme_options = {
    "source_repository": "https://github.com/VanaMartin/qscat/",
    "source_branch": "main",
    "source_directory": "docs/",
    "light_css_variables": {
        "color-brand-primary": "#1a5490",
        "color-brand-content": "#1a5490",
    },
    "dark_css_variables": {
        "color-brand-primary": "#7cb3e8",
        "color-brand-content": "#7cb3e8",
    },
}
