"""The level-aware energy mesh for O2's VE sweep, written into the example
config.

`python -m validation.factory.o2_ve_energies [--out apps/qscat-run/examples/o2-ve.yaml]`

O2's VE cross section is a comb of narrow peaks at the anion's quasi-bound
levels (`validation/factory/results/o2-anion-levels.csv`, the spectral
check's own output): widths run from 0.01 meV near the bottom to ~8 meV at
2 eV, so a uniform sweep at any affordable step walks past most of them. The
mesh here is a coarse background grid over the whole window plus a dense
window of `N_WINDOW` points spanning `+-HALF_WIDTHS * max(Gamma_v, GAMMA_FLOOR)`
around each level (the floor keeps a sub-0.1-meV peak visible at all;
resolving its true shape would need the TD route). The list is what
`qscat-run`'s `energies: {values: [...]}` takes.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
from qscat.units import EV_TO_HARTREE

__all__ = ["level_aware_energies", "main"]

LEVELS = Path("validation/factory/results/o2-anion-levels.csv")
E_WINDOW = (0.002, 0.100)  # Ha
BACKGROUND_STEP = 0.0005  # Ha (13.6 meV)
# 121 points across +-6 widths puts the mesh Gamma/10 apart, so every peak's
# shape is drawn, not just its maximum (height to 1 %). The history that
# set it: 15 points (Gamma/1.5 apart) read every peak height 0.6-0.9x its
# converged value -- a Gamma/3 miss on a Lorentzian is a factor 0.69, i.e.
# the mesh, not the model -- and 41 points (Gamma/4) gave them to ~10 %.
# ~3300 energies per model: ~22 min with MUMPS, not a laptop job.
N_WINDOW = 121
HALF_WIDTHS = 6.0
GAMMA_FLOOR = 0.3e-3 * EV_TO_HARTREE  # 0.3 meV


def level_aware_energies(levels_csv: Path = LEVELS) -> np.ndarray:
    table = np.loadtxt(levels_csv, delimiter=",", skiprows=1)
    E_v = table[:, 2] * EV_TO_HARTREE  # the fitted model's own levels
    G_v = np.maximum(table[:, 4] * EV_TO_HARTREE, GAMMA_FLOOR)
    lo, hi = E_WINDOW
    E = [np.arange(lo, hi + 0.5 * BACKGROUND_STEP, BACKGROUND_STEP)]
    for e, g in zip(E_v, G_v, strict=True):
        if lo < e < hi:
            E.append(np.linspace(e - HALF_WIDTHS * g, e + HALF_WIDTHS * g, N_WINDOW))
    allE = np.unique(np.round(np.concatenate(E), 8))
    return allE[(allE >= lo) & (allE <= hi)]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out", type=Path, default=Path("apps/qscat-run/examples/o2-ve.yaml"))
    ap.add_argument("--levels", type=Path, default=LEVELS, help="the component's level table")
    ap.add_argument("--molecule", default="O2", help="O2, O2_SO12 or O2_SO32")
    a = ap.parse_args()
    E = level_aware_energies(a.levels)
    values = ", ".join(f"{e:.6f}" for e in E)
    which = {
        "O2": "the unsplit 2Pi_g model (`qscat.model.O2`)",
        "O2_SO12": "the 2Pi_{1/2} spin-orbit component (`qscat.model.O2_SO12`)",
        "O2_SO32": "the 2Pi_{3/2} spin-orbit component (`qscat.model.O2_SO32`)",
    }[a.molecule]
    text = f"""# qscat-run example: O2 vibrational-excitation (VE), time-independent (TI),
# on the potential factory's FITTED O2 model -- {which}; Alt &
# Houfek, PRA 103, 032829 (2021), Fig. 2 reproduced to its extraction floor;
# docs/physics/potential-factory.md.
#
# GENERATED by `python -m validation.factory.o2_ve_energies` -- edit that,
# not this. O2's VE cross section is a comb of NARROW peaks at the anion's
# quasi-bound levels (widths 0.01-8 meV), so the energies are a level-aware
# mesh: a {BACKGROUND_STEP * 1e3:.0f} mHa background grid plus {N_WINDOW} points across
# +-{HALF_WIDTHS:.0f} widths of every level in the window, from the model's own
# levels (`validation/factory/results/{a.levels.name}`); {E.size} energies.
# Elastic + 0->1..5, the six panels of the paper's Fig. 5.
#
# The `tuner` preset is the discretisation tuner's deck, nuclear grid refined
# once by the 2-D spot check (178k unknowns): minutes per energy with SuperLU
# on a laptop, seconds with MUMPS -- run it in the Docker `test-deps` image on
# a machine with room.
#
# Run:
#   qscat-run validate {a.out}
#   qscat-run run {a.out} --output runs/{a.out.stem}

molecule: {a.molecule}
methods: [ti]

observables:
  - {{kind: ve, channels: 6}}

energies:
  values: [{values}]

v_init: 0

grid: {{preset: tuner}}

artifacts:
  cross_section: true

backend: auto
output_dir: runs/{a.out.stem}
"""
    a.out.write_text(text)
    print(f"[O2] wrote {a.out}: {E.size} energies in [{E[0]:.4f}, {E[-1]:.4f}] Ha")


if __name__ == "__main__":
    main()
