"""Tests for the NO/F2 exact-2D TI cross-section oracle (the model port).

There is no independent golden data for NO/F2 (only N2 has Houfek's data), so
these gate the exact solver's own well-posedness (real, finite, non-negative σ
of the right shape) plus the physical fact that each molecule has a low-lying
resonance producing a strong vibrational-excitation cross section -- computed
entirely through the promoted `qscat.core` + `qscat.model` library. The full
dense σ(E) curves + figures are generated by `curves.main()` (committed under
`docs/physics/figures/`), not re-run here.
"""

from __future__ import annotations

import numpy as np
import pytest
from qscat.core.driven import ve_cross_section
from qscat.core.grids import electronic_grid, nuclear_grid
from qscat.core.vibrational import vibrational_states
from qscat.dvr import TensorGrid

from validation.diatomic.config import CONFIGS, MoleculeConfig
from validation.diatomic.curves import VPRIMES, compute_ti_curve


def _small_tgrid() -> TensorGrid:
    """Tiny, deliberately unconverged grid -- fast shape/finiteness checks only."""
    return TensorGrid(
        [
            electronic_grid(r_max=14.0, order=6, n_complex=4),
            nuclear_grid(r_max=20.0, quadrature=8, n_complex=4),
        ]
    )


def test_no_and_f2_are_configured() -> None:
    assert set(CONFIGS) == {"NO", "F2"}
    assert CONFIGS["NO"].model.ell == 1 and CONFIGS["F2"].model.ell == 1
    assert CONFIGS["NO"].model.mu == 13614.16
    assert CONFIGS["F2"].model.mu == 17315.99


@pytest.mark.parametrize("name", ["NO", "F2"])
def test_ti_curve_shape_and_physical(name: str) -> None:
    """On a small grid at a few energies: σ real, finite, ≥0, right shape."""
    cfg: MoleculeConfig = CONFIGS[name]
    tg = _small_tgrid()
    eps, chi = vibrational_states(tg.grids[1], cfg.model.mu, cfg.n_vib, cfg.model.v0)
    E = np.array([0.02, 0.04, 0.06])
    sigma = ve_cross_section(tg, cfg.model, eps, chi, 0, VPRIMES, E)
    assert sigma.shape == (len(E), len(VPRIMES))
    assert sigma.dtype == np.float64
    assert np.all(np.isfinite(sigma))
    assert np.all(sigma >= 0.0)
    # neutral vibrational spacing is the small, molecule-specific value
    assert 0.001 < (eps[1] - eps[0]) < 0.02


@pytest.mark.parametrize("name", ["NO", "F2"])
def test_low_energy_resonance_drives_vibrational_excitation(name: str) -> None:
    """On the converged working grid: each molecule's low-lying resonance
    produces a strong v'=1 excitation cross section somewhere in its resonance
    window -- the physical signature the exact-2D solver must reproduce for the
    port to be meaningful. A couple of energies only (seconds), not the full
    curve."""
    cfg = CONFIGS[name]
    E = np.array([0.024, 0.036]) if name == "F2" else np.array([0.030, 0.044])
    _, sigma, _ = compute_ti_curve(cfg, E)
    assert np.all(sigma >= 0.0) and np.all(np.isfinite(sigma))
    # strong resonant vibrational excitation: v'=1 exceeds ~0.3 bohr^2 at a peak
    assert sigma[:, 1].max() > 0.3
